<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="HCLT-PC5929-1" failures="1" tests="1" name="com.hcl.gim.testscripts.foundation_bonus.TYSS_GIM_FB_0013" time="281.589" errors="0" timestamp="25 Feb 2021 23:13:04 GMT" skipped="0">
  <testcase classname="com.hcl.gim.testscripts.foundation_bonus.TYSS_GIM_FB_0013" name="TC_TYSS_GIM_FB_0013" time="281.589">
    <failure message="Previous record page is not loaded within 120 seconds" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Previous record page is not loaded within 120 seconds
at org.testng.Assert.fail(Assert.java:96)
at com.hcl.gim.pages.PreviousRecords_Page.validatePreviousRecordsPage(PreviousRecords_Page.java:595)
at com.hcl.gim.testscripts.foundation_bonus.TYSS_GIM_FB_0013.TC_TYSS_GIM_FB_0013(TYSS_GIM_FB_0013.java:218)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- TC_TYSS_GIM_FB_0013 -->
</testsuite> <!-- com.hcl.gim.testscripts.foundation_bonus.TYSS_GIM_FB_0013 -->
